name: ogb-prod

services:
  api:
    image: ghcr.io/opengamebuilder/opengamebuilder-api:production
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    networks:
      ogb-edge:
        aliases:
          - api-production

networks:
  ogb-edge:
    external: true
