name: ogb-preview

services:
  api:
    image: ghcr.io/opengamebuilder/opengamebuilder-api:preview
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Preview
      ASPNETCORE_URLS: http://+:8080
    networks:
      ogb-edge:
        aliases:
          - api-preview

networks:
  ogb-edge:
    external: true
