name: ogb-staging

services:
  api:
    image: ghcr.io/opengamebuilder/opengamebuilder-api:staging
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_URLS: http://+:8080
    networks:
      ogb-edge:
        aliases:
          - api-staging

networks:
  ogb-edge:
    external: true
