name: 🚀 CD Production

on:
  push:
    tags:
      - "v*"

concurrency:
  group: cd-production
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./_deploy.yml
    with:
      environment-slug: production
      dotnet-environment: Production
    secrets: inherit
