name: 🧱 CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore tools
        run: dotnet tool restore

      - name: Restore
        run: dotnet restore opengamebuilder.slnx

      - name: Build
        run: dotnet build opengamebuilder.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test opengamebuilder.slnx --configuration Release --no-build
